Adding Hinton knowledge distillation
IvLabs/stagewise-knowledge-distillation pull request #13
Opened 2020-08-10 18:04 UTC by RajGhugare19

2020-08-10 18:07 UTC, akshaykvnit commented on trainer.py
> +from comet_ml import Experiment
this file is extra. Please remove it.

2020-08-10 18:13 UTC, akshaykulkarni07 requested changes
Remove the extra file. Rest seems fine, but I'll still request @navidpanchi to just go through once.

2020-08-10 18:18 UTC, akshaykvnit commented
Another thing @RajGhugare19, you have to update the README file (see how other methods are mentioned in the main README and do the same).

2020-08-11 07:07 UTC, RajGhugare19 commented
I have deleted the extra file and updated the README @akshaykvnit

2020-08-12 13:07 UTC, navidpanchi approved these changes

2020-08-15 04:58 UTC, merged